server:
  host:
  port:
  mode:
  appVersion:
bot:
  token:
postgres:
  host:
  port:
  user:
  password:
  dbname:
  SslMode:
crawler:
  time:
  seeds:
    - url:
      source:
    - url:
      source:
  generalLogPath:
  metricLogPath:
logger:
  level:
  encoding:
  path:
  sysPath:
redis:
  host:
  port:
  password:
  db:
