server:
  host:
  port:
  mode:
  appVersion:
bot:
  token:
postgres:
  host:
  port:
  user:
  password:
  dbname:
  SslMode:
crawler:
  crawlTime:
logger:
  level:
  encoding:
  path:
  sysPath:
redis:
  host: localhost
  port: 6379
  password:
  db: test
