apiVersion: batch/v1
kind: CronJob
metadata:
  name: magic-crawler-crawler
  namespace: magic-crawler
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: arvan-registry-secret
          containers:
            - name: crawler
              image: registry-c8b30dd0eb-magic-crawler.apps.ir-central1.arvancaas.ir/magic-crawler:6b8a626
              args: ["crawler", "-c", "/opt/app/config.yaml"]
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/app
                - name: log-volume
                  mountPath: /var/log
          restartPolicy: OnFailure
          volumes:
            - name: config-volume
              configMap:
                name: magic-crawler-config
            - name: log-volume
              emptyDir: {}