server:
  host:
  port:
  mode:
  appVersion:
bot:
  token:
postgres:
  postgresqlHost:
  postgresqlPort:
  postgresqlUser:
  postgresqlPassword:
  postgresqlDbname:
  postgresqlSslmode:
crawler:
  crawlTime:
logger:
  level:
  encoding:
  path:
