server:
  host:
  port:
  mode:
  appVersion:
bot:
  token:
postgres:
  ConnectionURI:
  PostgresqlHost:
  PostgresqlPort:
  PostgresqlUser:
  PostgresqlPassword:
  PostgresqlDbname:
  PostgresqlSslmode:
  PgDriver:
crawler:
  crawlTime:
logger:
  level:
  encoding:
  path:
