version: "2"

sql:
  - engine: "postgresql"
    schema: "../pkg/db/migration/"
    queries: "../pkg/db/query/"
    gen:
      go:
        package: "sqlc"
        out: "../pkg/db/sqlc"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_pointers_for_null_types: true
        overrides:
          - db_type: "pg_catalog.timestamp"
            go_type:
              import: "time"
              type: "Time"
            nullable: true
          - db_type: "pg_catalog.numeric"
            go_type:
              pointer: true
              type: "float64"
            nullable: true
          - db_type: "ad_category"
            go_type:
              type: "string"
            nullable: true
          - db_type: "ad_category"
            go_type:
              type: "string"
            nullable: false
          - db_type: "house_type"
            go_type:
              type: "string"
            nullable: true
          - db_type: "house_type"
            go_type:
              type: "string"
            nullable: false
