name: Go CI-CD Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./... -v

  lint:
    name: Run Go Lint
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Install GolangCI-Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0

      - name: Run GolangCI-Lint
        run: golangci-lint run ./...

build-and-push:
  name: Build and Push Combined Docker Image
  runs-on: ubuntu-latest
  needs: lint

  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login registry-c8b30dd0eb-magic-crawler.apps.ir-central1.arvancaas.ir -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Extract Short Commit Hash
      id: vars
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          registry-c8b30dd0eb-magic-crawler.apps.ir-central1.arvancaas.ir/magic-crawler:latest
          registry-c8b30dd0eb-magic-crawler.apps.ir-central1.arvancaas.ir/magic-crawler:${{ env.SHORT_SHA }}